name: Test 2

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
  conclusion:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        run:
          exit 0
